version: '3'

services:
  dns:
    image: internetsystemsconsortium/bind9:9.16
    restart: always
    ports:
      - 553:53/udp
      - 553:53/tcp
      - 127.0.0.1:953:953/tcp
    volumes:
      - ./bind:/etc/bind
      - cache:/var/cache/bind
      - ./zones:/var/lib/bind

volumes:
  cache: