# Your Orion member id
id = 1
# You NEED to thange this value
private_key = "8KgygvpN8j78VLO+ULIEwmfxBiPPEekOgiRbj5j0T3Q="
# You can remove this line if you do not plan on openning  port on your router.
# listen = 45600
asn = 64517

# Peers configuration
[[peers]]
id = 1
public_key = "cD0RK3Jt5duamdeXkw57vzAkXo+7qxq+JXTUBzuCCxc="
endpoint = "r1.peering.matthieu-dev.xyz:45600"
asn = 64512