version: '3'

services:
   routinator:
      image: nlnetlabs/routinator
      ports:
         - 0.0.0.0:3323:3323
         - 0.0.0.0:8323:8323
      command: --no-rir-tals --extra-tals-dir="/tals" server --rtr [::]:3323 --http [::]:8323
      volumes:
         - ./routinator.conf:/etc/routinator.conf
         - ./tals:/tals
